# -*- coding: utf-8 -*-
"""practice_4embeddingModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19DWrZV1XlOoNA5oMoCLGRTkKI0tM5ZaS

## 1. 라이브러리
"""

!pip install konlpy
!pip install gensim==3.7.0 --user
import urllib.request
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import re
from konlpy.tag import Okt
from io import BytesIO
from gensim.models import Word2Vec
from gensim.models import KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity

"""## 2. 텍스트 전처리"""

df = pd.read_csv('/content/bookdata.csv')

def _removeNonAscii(text):
    letters_only = re.sub('[^ 0-9가-힣]', '', text)   
    return letters_only

def remove_stop_words(text):    
    
    okt = Okt()
    tokenized_data = []
    #temp_X = twitter.nouns(text) # 토큰화
    temp_X = okt.morphs(text, stem=True) # 토큰화
    
    tokenized_data.append(temp_X)
    return( ' '.join(temp_X) )

df['cleaned'] = df['review'].apply(_removeNonAscii)
df['cleaned'] = df['cleaned'].apply(remove_stop_words)

corpus=df['cleaned']
print(corpus[:30])

corpus=[]
for words in df['cleaned']:
    corpus.append(words.split())

"""## 3. 단어 임베딩 모델 만들기 (Fasttext)"""

# FastText
!pip install FastText
from gensim.models import FastText 
from tqdm import tqdm 

print("학습 중") 

model = FastText(corpus, size=100, workers=4, sg=1, iter=6, word_ngrams=5) 
model_fname = 'fasttext_model'
model.save(model_fname) # https://projector.tensorflow.org/ 에서 시각화 하기 위해 모델을 따로 저장 
model.wv.save_word2vec_format(model_fname + "_vis") 
print('완료')

print(model.wv.vocab)
print(model.wv.most_similar("바람", topn=5))

"""## 4. 단어 임베딩 모델 만들기 (Glove)


"""

! git clone https://github.com/stanfordnlp/glove
! pip install glove_python_binary
# import 해서 불러옵니다.
from glove import Corpus, Glove

Corpus().fit(corpus, window=20)

# model
glove = Glove(no_components=128, learning_rate=0.01)     # 0.05
glove.fit(pd.DataFrame(corpus), epochs=50, no_threads=4, verbose=False)   
glove.add_dictionary(corpus.dictionary)

# save
glove.save('glove_w20_epoch50.model')

